# Docker Compose 파일 포맷 버전 지정
version: "2.2"
services:
  ubuntu:
    container_name: vscode-server
    build:
      context: ./
      dockerfile: Dockerfile
    image: oseongryu/vscode-server
    volumes:
      - ~/git:/git
    ports:
      - "8080:8080"
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    privileged: true
