# Docker Compose 파일 포맷 버전 지정
version: "2.2"
services:
  redis:
    container_name: env-redis
    build:
      context: ./
      dockerfile: Dockerfile
    image: oseongryu/redis
    ports:
      - "6379:6379"
    restart: always
    stdin_open: true # docker run -i
    tty: true # docker run -t
    privileged: true
