# Docker Compose 파일 포맷 버전 지정
version: "1.0"

services:
  oracle:
    container_name: db-oracle-emt
    volumes:
      - ./db/static:/app
    build:
      context: ./db/
      dockerfile: Dockerfile
    image: db/oracle-xe-11g:latest
    environment:
      - ORACLE_ALLOW_REMOTE=true
    ports:
      - "1521:1521"
    stdin_open: true # docker run -i
    tty: true        # docker run -t