# Docker Compose 파일 포맷 버전 지정
version: "1.0"

services:
  oracle:
    container_name: db-oracle
    build:
      context: ./01_oracle/
      dockerfile: Dockerfile
    image: db/oracle-xe-11g:latest
    environment:
      - ORACLE_ALLOW_REMOTE=true
    ports:
      - "1521:1521"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  mysql:
    container_name: db-mysql
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    build:
      context: ./02_mysql/
      dockerfile: Dockerfile
    image: db/mysql:5.7
    environment:
      - LC_ALL=C.UTF-8
      - MYSQL_DATABASE=MYDB
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  mongodb:
    container_name: db-mongodb
    build:
      context: ./03_mongodb/
      dockerfile: Dockerfile
    image: db/mongo:3.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=DB_ADMIN
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=db
    ports:
      - "27017:27017"
    stdin_open: true # docker run -i
    tty: true        # docker run -t