# Docker Compose 파일 포맷 버전 지정
version: "2.2"
services:
  ubuntu:
    container_name: ubuntu-desktop
    build:
      context: ./
      dockerfile: Dockerfile
    image: oseongryu/ubuntu-desktop
    volumes:
      - ~/git:/git
      - ./script:/root/script
    ports:
      - "13389:3389"
    restart: always
    stdin_open: true # docker run -i
    tty: true # docker run -t
    privileged: true
