# Docker Compose 파일 포맷 버전 지정
version: "1"

# 컨테이너 설정
services:
  jekyll:
    container_name: centos-jekyll
    # image: jekyll/ruby:0.0.1
    build:
      context: ./
      # dockerfile: Dockerfile
    # restart: always
    # 컨테이너에서 사용하는 volume 설정으로 대체 가능(옵션)
    volumes:
      - /c/Users/osryu/git-personal/test:/usr/src/app
    stdin_open: true
    tty: true
    ports:
      - "4000:4000"
    # 컨테이너 간 네트워크 분리를 위한 추가 설정 부분(옵션)
