# Docker Compose 파일 포맷 버전 지정
version: "1"
name: env

# 컨테이너 설정
services:
  centos-env-vue:
    image: oseongryu/centos-env-vue:0.0.3
    container_name: centos-env-vue
    # restart: always
    volumes:
      # - ./vue/nginx:/etc/nginx/conf.d/
      - ~/git/hy-fredit-web:/hy-fredit-web/
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "9551:9551"
      - "9552:9552"