# https://www.digitalocean.com/community/tutorials/how-to-enable-remote-desktop-protocol-using-xrdp-on-ubuntu-22-04
# Docker Compose 파일 포맷 버전 지정
version: "2.2"
services:
  python1:
    container_name: shorts-python1
    volumes:
      - ~/git:/root/git
      - ~/DEV/shorts:/root/DEV/shorts
    build:
      context: ./python/
      dockerfile: Dockerfile
    image: shorts/python:1.0.0
    ports:
      - "8091:8091"
    privileged: true
    restart: always
    stdin_open: true # docker run -i
    tty: true # docker run -t
  python2:
    container_name: shorts-python2
    volumes:
      - ~/git:/root/git
      - ~/DEV/shorts:/root/DEV/shorts
    build:
      context: ./python/
      dockerfile: Dockerfile
    image: shorts/python:1.0.0
    ports:
      - "8092:8091"
    privileged: true
    restart: always
    stdin_open: true # docker run -i
    tty: true # docker run -t
  python3:
    container_name: shorts-python3
    volumes:
      - ~/git:/root/git
      - ~/DEV/shorts:/root/DEV/shorts
    build:
      context: ./python/
      dockerfile: Dockerfile
    image: shorts/python:1.0.0
    ports:
      - "8093:8091"
    privileged: true
    restart: always
    stdin_open: true # docker run -i
    tty: true # docker run -t
  python4:
    container_name: shorts-python4
    volumes:
      - ~/git:/root/git
      - ~/DEV/shorts:/root/DEV/shorts
    build:
      context: ./python/
      dockerfile: Dockerfile
    image: shorts/python:1.0.0
    ports:
      - "8094:8091"
    privileged: true
    restart: always
    stdin_open: true # docker run -i
    tty: true # docker run -t
  python5:
    container_name: shorts-python5
    volumes:
      - ~/git:/root/git
      - ~/DEV/shorts:/root/DEV/shorts
    build:
      context: ./python/
      dockerfile: Dockerfile
    image: shorts/python:1.0.0
    ports:
      - "8095:8091"
    privileged: true
    restart: always
    stdin_open: true # docker run -i
    tty: true # docker run -t
