CREATE TABLE `DEMO`.`TEST`
(
  TEST_SEQ_NO INT NOT NULL AUTO_INCREMENT
, CONTENT VARCHAR(100) NOT NULL
, CONSTRAINT PK_TEST PRIMARY KEY
  (
    TEST_SEQ_NO
  )
);


ALTER TABLE DEMO.TEST COMMENT '테스트';