# Docker Compose 파일 포맷 버전 지정
version: "1"

# 컨테이너 설정
services:
  db:
    image: mysql:5.7
    restart: always
    # 컨테이너에서 사용하는 volume 설정으로 대체 가능(옵션)
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASES=mydb
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "3306:3306"
    # # 컨테이너 간 네트워크 분리를 위한 추가 설정 부분(옵션)
    # network: