# Docker Compose 파일 포맷 버전 지정
version: "1"
name: nuxt-fredit

# 컨테이너 설정
services:
  vue:
    container_name: centos-vue
    build:
      context: ./vue/
      dockerfile: Dockerfile
    image: oseongryu/centos-vue:1.0.0
    # restart: always
    # 컨테이너에서 사용하는 volume 설정으로 대체 가능(옵션)
    volumes:
      # - ./vue/app:/app/
      - ./vue/script:/app/script/
    ports:
      - "80:80"
    # 컨테이너 간 네트워크 분리를 위한 추가 설정 부분(옵션)
    # entrypoint: ["sh", "-c"]
    # command:
    #   - |
    #     /app/script/start_nginx.sh
    stdin_open: true
    tty: true
