# Docker Compose 파일 포맷 버전 지정
version: "1.0"
services:
  mysql:
    container_name: db-mysql
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    build:
      context: ./02_mysql/
      dockerfile: Dockerfile
    image: db/mysql:5.7
    environment:
      - LC_ALL=C.UTF-8
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=testdb1234
    ports:
      - "13306:3306"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
