FROM openjdk:8
# VOLUME /tmp
# EXPOSE 8089
# ADD target/SpringBootDockerTest-0.0.1-SNAPSHOT.jar SpringBootDockerTest-0.0.1-SNAPSHOT.jar 
ENTRYPOINT ["java","-jar","/usr/local/tomcat/webapps/drawing-app.war"] 