# Docker Compose 파일 포맷 버전 지정
version: "2.2"
services:
  vscode-server:
    container_name: vscode-server
    build:
      context: ./vscode-server
      dockerfile: Dockerfile
    image: oseongryu/vscode-server
    volumes:
      - ~/git:/git
    ports:
      - "8080:8080"
    restart: always
    stdin_open: true # docker run -i
    tty: true # docker run -t
    privileged: true
  jekyll:
    container_name: centos-jekyll
    # image: jekyll/ruby:0.0.1
    build:
      context: ./jekyll
      dockerfile: Dockerfile
    # restart: always
    # 컨테이너에서 사용하는 volume 설정으로 대체 가능(옵션)
    volumes:
      - /c/Users/osryu/git-personal/test:/usr/src/app
    stdin_open: true # docker run -i
    tty: true # docker run -t
    ports:
      - "4000:4000"
    # 컨테이너 간 네트워크 분리를 위한 추가 설정 부분(옵션)
