---
version: "3.5"

services:
  webtop:
    container_name: webtop
    image: linuxserver/webtop:arm64v8-ubuntu-xfce
    volumes:
      - ~/git/docker-ubuntu-vnc-desktop:/src
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
    ports:
      - "3000-3010:3000"
      - "3011-3020:3001"
    restart: always
    stdin_open: true # docker run -i
    tty: true # docker run -t
    privileged: true
  webtop-custom:
    build:
      context: ./
      dockerfile: Dockerfile
    image: webtop-custom:latest
    container_name: webtop-custom
    hostname: webtop
    restart: unless-stopped
    privileged: true
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - SUBFOLDER=/
      - TITLE=liveLinux
      - RESET_HOME=true
      - DESKTOP_ICONS=false
      - DISABLE_IPV6=true
      # HTTP Basic Auth 사용시 ID/PW
      #- CUSTOM_USER=abc
      #- PASSWORD=abc
    volumes:
      # - "./data:/config"
      # - "./docker:/var/lib/docker"
      # 사설 인증서 등록 필요시 사용
      # - "./certificates:/usr/local/share/ca-certificates"
      # 호스트 도커연동 제외
      #- '/var/run/docker.sock:/var/run/docker.sock'
      # Shared Memory는 호스트와 연동하여 사용
      - "/dev/shm:/dev/shm"
    ports:
      - "3000-3010:3000"
      - "3011-3020:3001"
    devices:
      - /dev/dri:/dev/dri
# https://github.com/kasmtech/KasmVNC/releases/download/v1.3.1/kasmvncserver_focal_1.3.1_arm64.deb

# # Please choose the package for your distro here (under Assets):
# # https://github.com/kasmtech/KasmVNC/releases
# wget https://github.com/kasmtech/KasmVNC/releases/download/v1.3.1/kasmvncserver_focal_1.3.1_arm64.deb
# sudo apt-get install ./kasmvncserver_*.deb
# # Add your user to the ssl-cert group
# sudo addgroup $USER ssl-cert

# # Start a session and be guided to setup a user and select a default desktop environment
# vncserver
# # Start a session with the mate desktop environment
# vncserver -select-de mate
# # Add a new user with read/write permissions
# vncpasswd -u my_username -w -r
# # Tail the logs
# tail -f ~/.vnc/*.log
# # Get a list of current sessions with display IDs
# vncserver -list
# # Kill the VNC session with display ID :2
# vncserver -kill :2
# https://www.digitalocean.com/community/tutorials/how-to-enable-remote-desktop-protocol-using-xrdp-on-ubuntu-22-04

