# https://www.digitalocean.com/community/tutorials/how-to-enable-remote-desktop-protocol-using-xrdp-on-ubuntu-22-04
# Docker Compose 파일 포맷 버전 지정
version: "2.2"
services:
  python:
    container_name: automation-python
    volumes:
      - ~/git:/root/git
    build:
      context: ./python/
      dockerfile: Dockerfile
    # image: automation/pyton:1.0.0
    image: automation/python:1.0.0
    ports:
      - "8088:8088"
    privileged: true
    restart: always
    stdin_open: true # docker run -i
    tty: true # docker run -t
  # was:
  #   container_name: automation-was
  #   volumes:
  #     - ./was/static:/root/app
  #   build:
  #     context: ./was/
  #     dockerfile: Dockerfile
  #   image: automation/was:1.0.0
  #   ports:
  #     - "8089:8089"
  #   stdin_open: true # docker run -i
  #   tty: true        # docker run -t
  desktop:
    container_name: automation-desktop
    build:
      context: ./desktop/
      dockerfile: Dockerfile
    image: automation/desktop:1.0.0
    ports:
      - "13389:3389"
      - "3000:3000"
      - "8080:8080"
    restart: always
    stdin_open: true # docker run -i
    tty: true # docker run -t
    privileged: true
