version: "2.2"
services:
  cli:
    container_name: automation-cli
    build:
      context: ./cli/
      dockerfile: Dockerfile
    image: oseongryu/automation-cli:1.0.0
    ports:
      - "8088:8088"
    volumes:
      - ~/git:/root/git
    restart: always
    stdin_open: true # docker run -i
    tty: true # docker run -t
    privileged: true
  desktop:
    container_name: automation-desktop
    build:
      context: ./desktop/
      dockerfile: Dockerfile
    image: oseongryu/automation-desktop:1.0.0
    ports:
      - "13389:3389"
      - "80:8091"
    volumes:
      - ~/git:/git
    restart: always
    stdin_open: true # docker run -i
    tty: true # docker run -t
    privileged: true
