-- 테이블 스페이스 생성
CREATE TABLESPACE TESTDB_DATA  datafile '/u01/app/oracle/oradata/XE/TESTDB_DATA.dbf' SIZE 100M AUTOEXTEND on next 100M;
-- 임시 테이블스페이스 생성
CREATE TEMPORARY TABLESPACE TESTDB_DATA_TEMP  TEMPFILE  '/u01/app/oracle/oradata/XE/TESTDB_DATA_TEMP.dbf' SIZE 100M AUTOEXTEND on next 10M;

-- 계정생성
CREATE USER testdb  IDENTIFIED BY  "1234"
DEFAULT TABLESPACE TESTDB_DATA
TEMPORARY TABLESPACE TESTDB_DATA_TEMP
QUOTA UNLIMITED ON TESTDB_DATA;

-- 접속 권한주기
GRANT RESOURCE, CONNECT to testdb;
-- 테이블스페이스 사용권한
GRANT UNLIMITED TABLESPACE TO testdb;